- name: "Copy service {{ item.service }} to {{ firewalld.service_path }}"
  vars:
    service: "{{ item.service }}"
    description: "{{ item.description }}"
    port: "{{ item.port }}"
    protocol: "{{ item.protocol }}"
  template:
    src: "port_service.xml"
    dest: "{{ firewalld.service_path }}/port-{{ service }}.xml" 
    owner: root
    group: root
    mode: '0664'
  notify:
    - Reload service firewalld
# https://docs.ansible.com/ansible/latest/modules/template_module.html 
# https://chmodcommand.com/ 